/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernanceStateChangeTargetStub } from "./GovernanceStateChangeTargetStub";
export type { GovernanceTargetAlphaStub } from "./GovernanceTargetAlphaStub";
export type { GovernanceTargetConstructorArgumentStub } from "./GovernanceTargetConstructorArgumentStub";
export type { GovernanceTargetNumberStub } from "./GovernanceTargetNumberStub";
