name: Integration Tests (V2)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration-tests:
    name: 🧪 Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'
      - name: Checkout engine repo
        uses: actions/checkout@v3
        with:
          path: engine
      - name: Checkout contract repo
        uses: actions/checkout@v3
        with:
          repository: Railgun-Privacy/contract
          path: contract
      - name: Yarn in engine
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: 'engine'
      - name: Yarn in contract
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: 'contract'
      - name: Compile contract
        run: cd contract && npm run compile
      - name: Run contract hardhat and engine tests
        uses: BerniWittmann/background-server-action@v1
        with:
          command: cd contract && npm run deploy && cd ../engine && yarn coverage-hardhat-V2
          start: cd contract && npm run node >/dev/null
          wait-on: 'http://localhost:8545'
          wait-on-timeout: 120
      - name: Report coverage
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./engine/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
