name: Integration Tests (V3)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration-tests:
    name: 🧪 Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Checkout engine repo
        uses: actions/checkout@v3
        with:
          path: engine
      - name: Checkout contract repo
        uses: actions/checkout@v3
        with:
          repository: Railgun-Privacy/contract
          path: contract
      - name: Yarn in engine
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: 'engine'
      - name: Yarn in contract
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: 'contract'
      - name: Compile contract
        run: cd contract && npm run compile
      - name: Run contract hardhat and engine tests
        uses: BerniWittmann/background-server-action@v1
        with:
          start: cd contract && $(npm bin)/hardhat node >/dev/null
          command: cd contract && sleep 10 && $(npm bin)/hardhat deploy:test --network localhost && cd ../engine && yarn test-hardhat
