name: Integration Tests (V3)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration-tests:
    if: false # Disable this job while V3 isn't ready
    name: 🧪 Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Checkout engine repo
        uses: actions/checkout@v3
        with:
          path: engine
      - name: Checkout contract repo
        uses: actions/checkout@v3
        with:
          repository: Railgun-Privacy/contract
          path: contract
      - name: Yarn in engine
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: 'engine'
      - name: Yarn in contract
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: 'contract'
      - name: Compile contract
        run: cd contract && ./node_modules/.bin/hardhat compile
      - name: Run contract hardhat and engine tests
        uses: BerniWittmann/background-server-action@v1
        with:
          command: cd engine && yarn test-hardhat
          start: cd contract && npx hardhat node >/dev/null, cd contract && sleep 5 && npx hardhat deploy:test --network localhost >/dev/null
          wait-on: 'http://localhost:8545'
          wait-on-timeout: 120
